### ISSUE TITLE
Does not work at all - Runtime Error Traceback

### ISSUE THREAD

**Issue by DonKingMat** [izderadicka/imap_detach#10]
It is Independent how I try to run you tool. It will fail forever with a reason that could be understood.

$ python --version
Python 2.7.5

$ detach.py -H mail.your-server.de -u "user@mail.org" -p "NoStrongPass" -v 'attached' --verbose -t 5
Runtime Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/imap_detach/imap_client.py", line 164, in main
    c=IMAP_client_factory(host,port,use_ssl=ssl)
  File "/usr/lib/python2.7/site-packages/imap_detach/utils.py", line 81, in IMAP_client_factory
    return imapclient.IMAPClient(host,port,ssl=use_ssl, ssl_context=ssl_context, timeout=60)
  File "/usr/lib64/python2.7/site-packages/imapclient/imapclient.py", line 152, in __init__
    self._imap = self._create_IMAP4()
  File "/usr/lib64/python2.7/site-packages/imapclient/imapclient.py", line 164, in _create_IMAP4
    self._timeout)
  File "/usr/lib64/python2.7/site-packages/imapclient/tls.py", line 153, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "/usr/lib64/python2.7/imaplib.py", line 202, in __init__
    typ, dat = self.capability()
  File "/usr/lib64/python2.7/imaplib.py", line 374, in capability
    typ, dat = self._simple_command(name)
  File "/usr/lib64/python2.7/imaplib.py", line 1083, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib64/python2.7/imaplib.py", line 870, in _command
    self.send('%s%s' % (data, CRLF))
  File "/usr/lib64/python2.7/site-packages/imapclient/tls.py", line 171, in send
    sent = self.sock.send(data)
  File "/usr/lib/python2.7/site-packages/backports/ssl/core.py", line 281, in send
    return _safe_ssl_call(False, self._conn, 'send', data, flags)
  File "/usr/lib/python2.7/site-packages/backports/ssl/core.py", line 201, in _safe_ssl_call
    return getattr(sock, call)(*args, **kwargs) 

Another example also fails:

$ detach.py -H mail.your-server.de -u "user@mail.org" -p "NoStrongPass" mime=application/pdf
ERROR:imap_client:Invalid syntax of filter: Rule 'expr' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with '=application/pdf' (line 1, column 5).

Or look at this:

$ detach.py -H mail.your-server.de -u "user@mail.org" -p "NoStrongPass" mime = application/pdf
usage: detach.py [-h] -H HOST -u USER [-p PASSWORD] [--no-ssl]
                 [--insecure-ssl] [--folder FOLDER] [-f FILE_NAME]
                 [-c COMMAND] [-t THREADS] [-v] [--debug]
                 [--log-file LOG_FILE] [--test] [--seen] [--delete]
                 [--delete-file] [--move MOVE] [--timeit] [--no-imap-search]
                 [--unsafe-imap-search] [--version]
                 filter
detach.py: error: unrecognized arguments: = application/pdf

So 50% your description is not understood (how the hell it must be masqueraded?) and another 50% it crashes for unexplained reason.

Pls advice.

**Comment by izderadicka** [comment]
First problem is something in imapclient and its usage of ssl -  try it on python3 if it helps.
Other two errors are obvious
invalid syntax of the filter expression - it  should be passed as one argument - e.g.   surrounded by '  '  and text literals in filter should be surrounded by " ",  so command line should look like this:
```
detach.py -H mail.your-server.de -u "user@mail.org" -p "NoStrongPass" 'mime="application/pdf"'
```
